# Generated by Django 4.2.7 on 2023-11-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='lessons/')),
                ('image_alt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('afford', 'Afford'), ('time', 'Time'), ('needs', 'Time'), ('feed', 'Feed'), ('sleep', 'Sleep'), ('grooming', 'Grooming'), ('exercise', 'Exercise'), ('behaviour', 'Behaviour'), ('healthcare', 'Healthcare')], default='afford', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[('afford', 'Afford'), ('time', 'Time'), ('needs', 'Time'), ('feed', 'Feed'), ('sleep', 'Sleep'), ('grooming', 'Grooming'), ('exercise', 'Exercise'), ('behaviour', 'Behaviour'), ('healthcare', 'Healthcare')], default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
